Python Web Basics/exam_prep/notes/notes/note/urls.py
from django.urls import path
from notes.note import views

urlpatterns = [
    path('add/', views.create_note, name='create note'),
    path('edit/<int:id>', views.edit_note, name='edit note'),
    path('delete/<int:id>', views.delete_note, name='delete note'),
    path('details/<int:id>', views.show_note_details, name='details note'),
]

Python Web Basics/exam_prep/notes/notes/profiles/urls.py
from django.urls import path

from notes.profiles.views import show_profile, delete_profile

urlpatterns = [
    path('', show_profile, name='show profile'),
    path('delete/', delete_profile, name='delete profile'),
]

Python Web Basics/exam_prep/notes/notes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from notes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home page'),
    path('note/', include('notes.note.urls')),
    path('profile/', include('notes.profiles.urls')),
] + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

Python Web Basics/exam_prep/notes/notes/note/models.py
from django.db import models

# Create your models here.

class Note(models.Model):
    TITLE_MAX_LENGTH = 30

    title = models.CharField(
        max_length=TITLE_MAX_LENGTH,
    )

    image_url = models.URLField(

    )

    content = models.TextField(

    )

Python Web Basics/exam_prep/notes/notes/profiles/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
    FIRST_NAME_MAX_LENGTH = 20
    LAST_NAME_MAX_LENGTH = 20

    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LENGTH,
    )

    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LENGTH,
    )

    age = models.IntegerField(

    )

    image_url = models.URLField(

    )

Python Web Basics/exam_prep/notes/notes/note/forms.py
from django import forms

from notes.note.models import Note


class CreateNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'content', 'image_url')

class EditNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'content', 'image_url')

Python Web Basics/exam_prep/notes/notes/profiles/forms.py
from django import forms

from notes.profiles.models import Profile


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'age', 'image_url',)

Python Web Basics/exam_prep/notes/notes/note/views.py
from django.shortcuts import render, redirect

# Create your views here.
from notes.note.forms import CreateNoteForm, EditNoteForm
from notes.note.models import Note


def create_note(request):
    if request.method == 'POST':
        form = CreateNoteForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('home page')

    else:
        form = CreateNoteForm()

    context = {
        'form': form,
    }

    return render(request, 'note-create.html', context)


def edit_note(request, id):
    note = Note.objects.get(id=id)

    if request.method == 'POST':
        form = EditNoteForm(request.POST, instance=note)

        if form.is_valid():
            form.save()
            return redirect('home page')

    else:
        form = EditNoteForm(instance=note)

    context = {
        'form': form,
    }

    return render(request, 'note-edit.html', context)


def delete_note(request, id):
    note = Note.objects.get(id=id)

    if request.method == 'POST':
        note.delete()
        return redirect('home page')

    else:
        context = {
            'note': note,
        }

        return render(request, 'note-delete.html', context)


def show_note_details(request, id):
    note = Note.objects.get(id=id)

    context = {
        'note': note,
    }

    return render(request, 'note-details.html', context)

Python Web Basics/exam_prep/notes/notes/profiles/views.py
from django.shortcuts import render, redirect

# Create your views here.
from notes.note.models import Note
from notes.profiles.forms import CreateProfileForm
from notes.profiles.models import Profile


def get_profile():
    profiles = Profile.objects.all()

    if profiles:
        return profiles[0]
    return None


def show_profile(request):
    profile = get_profile()
    notes = Note.objects.all()

    notes_count = len(notes)

    context = {
        'notes_count': notes_count,
        'profile': profile,
    }

    return render(request, 'profile.html', context)


def delete_profile(request):
    profile = get_profile()
    notes = Note.objects.all()

    profile.delete()
    [note.delete() for note in notes]
    return redirect('home page')

Python Web Basics/exam_prep/notes/notes/views.py
from django.shortcuts import render

from notes.note.models import Note
from notes.profiles.forms import CreateProfileForm
from notes.profiles.views import get_profile


def create_profile(form):
    if form.is_valid():
        form.save()


def home_page(request):
    profile = get_profile()
    notes = Note.objects.all()

    if request.method == 'POST':
        form = CreateProfileForm(request.POST)
        create_profile(form)
        return render(request, 'home-with-profile.html')

    else:
        form = CreateProfileForm()

        context = {
            'form': form,
            'notes': notes,
        }

        if profile:
            return render(request, 'home-with-profile.html', context)
        return render(request, 'home-no-profile.html', context)

Python Web Basics/exam_prep/notes/templates/home-no-profile.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}

<div class="body">
    <!--headings-->
    <h1>Enter Your Data</h1>
    <!--end headings-->

    <!--profile data form-->
    <div class="form">
        <form method="POST">
            {#                    <input type="hidden" name="csrfmiddlewaretoken" value="97MmAxmrs7yPXUamEdIgRY80OHEP383f6VukAC6agPNIW60LqTcnIQlM6YCYPjc0" />#}
            {#                    <label for="firstName">First Name</label>#}
            {#                    <input type="text" name="first_name" maxlength="15" required="" id="id_first_name" />#}
            {##}
            {#                    <label for="lastName">Last Name</label>#}
            {#                    <input type="text" name="last_name" maxlength="15" required="" id="id_last_name" />#}
            {##}
            {#                    <label for="age">Age</label>#}
            {#                    <input type="number" name="age" required="" id="id_age" />#}
            {##}
            {#                    <label for="profilePhoto">Link to Profile Image</label>#}
            {#                    <input type="url" name="profile_image" required="" id="id_image" />#}

            {{ form }}

            {% csrf_token %}
            <input type="submit" value="SUBMIT"/>
        </form>
    </div>
    <!--end profile data form-->
</div>

{% endblock %}

Python Web Basics/exam_prep/notes/templates/home-with-profile.html
{% extends 'common/base.html' %}

{% block content %}

    <h1>My Notes</h1>

    {% if notes %}

    <!--notes container-->
    {% for note in notes %}
        <div class="note-container">
            <h2>{{ note.title }} <img src="{{ note.image_url }}"/></h2>

            <div class="right">
                <a class="button details" href="{% url 'details note' note.id %}">Details</a>
                <a class="button edit" href="{% url 'edit note' note.id %}">Edit</a>
                <a class="button delete" href="{% url 'delete note' note.id %}"">Delete</a>
            </div>
        </div>

    {% endfor %}



    {% else %}
    <h2>There are no notes.</h2>

    {% endif %}

{% endblock %}

Python Web Basics/exam_prep/notes/templates/note-create.html
{% extends 'common/base.html' %}

{% block content %}
        <div class="body">
            <!--headings-->
            <h1>Add Note</h1>
            <!--headings-->

            <!--note data form-->
            <div class="form">
                <form method="POST">
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="HUrRfZ1Xv8I1kg0RCRhg5I8sTJMRfcaLEI9Pf4LGjQXUjsQgoxLnWAleb0K01njw" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" maxlength="50" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{##}
{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" maxlength="200" required="" id="id_image_url" />#}
                    {{ form }}
                    {% csrf_token %}
                    <input type="submit" value="Publish" />
                </form>
            </div>
            <!--end note data form-->
        </div>
{% endblock %}

Python Web Basics/exam_prep/notes/templates/note-delete.html
{% extends 'common/base.html' %}

{% block content %}

        <div class="body">
            <!--headings-->
            <h1>Delete Note</h1>
            <!--headings-->

            <!--note delete data form-->
            <div class="form">
                <form method="POST">
                    <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc" />
                    <label for="name">Title</label>
                    <input type="text" name="title" value="{{ note.title}}" maxlength="50" disabled="" required="" id="id_title" />

                    <label for="content">Content</label>
                    <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">
{{ note.content }}

                    </textarea>

                    <label for="image_url">Link to Image</label>
                    <input type="url" name="image_url" value="{{ note.image_url }}" maxlength="200" disabled="" required="" id="id_image_url" />

                    {% csrf_token %}
                    <input type="submit" value="Delete" />
                </form>
            </div>
            <!--end note delete data form-->
        </div>

{% endblock %}

Python Web Basics/exam_prep/notes/templates/note-details.html
{% extends 'common/base.html' %}

{% block content %}



        <div class="body">
            <!--headings-->
            <h1>Note Details</h1>
            <!--headings-->

            <!--details note box-->
            <div class="note-details-container">
                <h2>{{ note.title}}</h2>
                <img class="detail-img" src="{{ note.image_url }}" alt="note-image" />
                <div>
                    <p>Content</p>
                </div>
                <p>
                    {{ note.content }}
                </p>
                <div class="right">
                    <a class="button edit" href="{% url 'edit note' note.id %}">Edit</a>
                    <a class="button delete" href="{% url 'delete note' note.id %}">Delete</a>
                </div>
            </div>
            <!--end details note box-->
        </div>

{% endblock %}

Python Web Basics/exam_prep/notes/templates/note-edit.html
{% extends 'common/base.html' %}

{% block content %}



        <div class="body">
            <!--headings-->
            <h1>Edit Note</h1>
            <!--headings-->

            <!--note edit data form-->
            <div class="form">
                <form method="POST">
{#                    <input type="hidden" name="csrfmiddlewaretoken" value="E8qoLvlyiXBfE7NlcyWlXe1TMWV5qvo7BW8mLA5h6FQ8DjDKYeqsO6eF4dTecGxS" />#}
{#                    <label for="name">Title</label>#}
{#                    <input type="text" name="title" value="Today's Tasks" maxlength="50" required="" id="id_title" />#}
{##}
{#                    <label for="content">Content</label>#}
{#                    <textarea name="description" cols="40" rows="10" required="" id="id_description">Today I need to go shopping, make some pancakes, and at the end of the day I should write some code.</textarea>#}
{##}
{#                    <label for="image_url">Link to Image</label>#}
{#                    <input type="url" name="image_url" value="https://www.freeiconspng.com/thumbs/tasks-icon/tasks-icon-9.png" maxlength="200" required="" id="id_image_url" />#}

                    {{ form }}
                    {% csrf_token %}

                    <input type="submit" value="Edit" />
                </form>
            </div>
            <!--end note edit data form-->
        </div>

{% endblock %}

Python Web Basics/exam_prep/notes/templates/profile.html
{% extends 'common/base.html' %}

{% block content %}


        <div class="body">
            <!--headings-->
            <h1>Your Profile</h1>
            <!--end headings-->

            <!--profile details container TODO-->
            <div class="note-container">
                <h2>
                    {{ profile.first_name }} {{ profile.last_name }}
                    <img src="{{ profile.image_url }}" />
                </h2>
                <p>Age: {{ profile.age }}</p>
                <div>
                    <p>All notes: {{ notes_count }}</p>
                </div>
                <div class="right">
                    <a class="button delete" href="{% url 'delete profile' %}">Delete</a>
                </div>
            </div>
            <!--end profile details container-->
        </div>

{% endblock %}